### ISSUE TITLE
Long lines in terminal scroll, when they should wrap instead. 

### ISSUE THREAD

**Issue by ioqy** [OliveTin/OliveTin#327]
**Describe the solution you'd like**

- [x] Text input fields are rather short. Especially considering that there is enough space to the right in the argument dialog. I can only enter around 22 characters before I can not see the beginning of the entered text. 
- [x] The new live command output is nice, but the black console does not fill the output dialog on the right. Even when maximizing the dialog the size of the console does not change.
- [x] #359
- [x] #361
- [x] This is minuscule but it would be nice if the title/label of text input fields would vertically align with the input field. At the moment the title/label is aligned with the top of the input field while the input field is about doule the height of the title/label.

**Comment by jamesread** [comment]
All of these are great suggestions, and things I know about (apart from the short inputs) - I appreciate you taking the time to write it up! 

I'll get to work - just doing a fix now for the terminal size as that's the most important.

**Comment by ioqy** [comment]
The live console now fits the dialog. But when maximizing the dialog the line breaks stay the same, which makes the output harder to read than without the live console. Is there a way to disable the live console?

And since 2024.06.02 I have this error at the bottom of the page:

![image](https://github.com/OliveTin/OliveTin/assets/95605581/cfae5d53-cba9-4e16-9051-1384b579b27c)

**Comment by jamesread** [comment]
@ioqy I assume the update message bit is fixed for you now?

**Comment by ioqy** [comment]
Yes, the update message is fixed.

**Comment by jamesread** [comment]
> Text input fields are rather short. Especially considering that there is enough space to the right in the argument dialog. I can only enter around 22 characters before I can not see the beginning of the entered text. 

Addressed in #360

**Comment by jamesread** [comment]
@ioqy Could you test version 2024.07.15 against your tick list in the first comment here?

**Comment by ioqy** [comment]
- [x] The width of the input fields is much better.
- [ ] While the live console now does fit the screen, the line breaks stay the same so the output is as hard to read as before.
- [ ] The dasbord name still gets removed from the URL when reloading the page.
- [ ] The burger menu still closes itself sometimes right after opening.
- [x] The vertical alignment of the labels is fixed.

**Comment by jamesread** [comment]
Sorry, I meant to point out that I'm going to track the "dashboard name URL" issue in #306 , and the burger menu issue in #361.

As for the width of the terminal window, yes, it had the issue of being too narrow (which is now fixed), but now long lines require scrolling, which isn't good. I'll leave this issue open to track that last issue.

**Comment by jamesread** [comment]
@ioqy 2024.08.14 has considerable improvements to terminal scaling / line wrapping, please could you check that looks better for you?

That version also includes better navigation - dashboards accessable at /myDashboard, etc, which should work fine on page refreshes. 

There was no change to the "burger menu".

**Comment by ioqy** [comment]
The terminal scaling and line wrapping is much better now. I only noticed that the output dialog doesn't go back to the normal height after maximizing and restoring (or even closing). It stays at almost the whole window height.

The URL now stays the same after a refresh.


There was another thing I noticed. Sometimes the output is shown twice. At first I thought that maybe the command is executed twice, but when displaying the time with nanoseconds it's clear that it's only the output:

![image](https://github.com/user-attachments/assets/3141acdd-1e0b-4390-b187-beb529ecd0c7)

Config:
```yaml
- title: Test
  shell: date --rfc-3339=ns
  popupOnStart: execution-dialog-stdout-only
```

Log:
```
INFO Action requested                              actionTitle="Test" tags="[]"
INFO Action parse args - Before                    actionTitle="Test" cmd="date --rfc-3339=ns"
INFO Action parse args - After                     actionTitle="Test" cmd="date --rfc-3339=ns"
INFO Action started                                actionTitle="Test" timeout="3"
INFO Action finished                               actionTitle="Test" exit="0" outputLength="36" timedOut="false"
```

**Comment by jamesread** [comment]
Hey @ioqy , I rebuilt how the nav sidebar animations worked in the last release, so that it's now just CSS, no JavaScript. I still dont think it's perfect, but better. 

I habe seen the duplicate output issue before, but let's discuss that in a new issue.

**Comment by ioqy** [comment]
The sidebar definetly feels better and I would say that it is very good and couldn't think of anything to improve.

**Comment by jamesread** [comment]
Thanks very much for your patience as I fixed the issues and implemented your feedback :-) I think that's everything, apart from the duplicate output bug (which I'll track in #401 . 

Closing this issue now, but let me know if I missed anything, or open new issues if you have new ideas!
