### ISSUE TITLE
Excessive log spam in action cause WebUI crash (Error getting buttons  TypeError: e.logs is undefined)

### ISSUE THREAD

**Issue by vttc08** [OliveTin/OliveTin#497]
**Describe the bug**
When an action produce excessive output is executed, if after one or many executions, the output exceed 4MB, the `/api/getLogs` cannot process any logs as maximum size is reached, producing `"grpc: received message larger than max (12000303 vs. 4194304)"`, it then crash the WebUI making it un-interactable, the start actions API still works.

**To Reproduce**
1. Install OliveTin via latest deb package on Linux using `dpkg -i`
2. Add any actions configuration that execute a shell script. In my script, I used it to cat a 64KB of junk file and looping it 50 times, producing ~3.2MB of output each execution.
3. Execute the action repeatedly in WebUI or API.
4. Refresh the page and observe `Error getting buttons TypeError: e.logs is undefined` error. The WebUI is frozen and no actions can be executed there.
5. Run `systemctl restart OliveTin` to make the WebUI usable before actions can be executed in the WebUI.

**Expected behavior**
The Web dashboard should remain usable such as being able to click on action or view logs, without needing periodic systemctl restart 

**Screenshots**
Video
https://github.com/user-attachments/assets/ac68bf8b-92a9-456c-9f1f-2c8d4a7262e5

**Additional context**
I use OliveTin as API gateway for Home Assistant to execute some automated actions. However, every week or so this error occurs and OliveTin become unusable but I can still use API to call actions. The [documentation](https://docs.olivetin.app/err-fetch-buttons.html) says it's due to bad proxy config but I'm using OliveTin directly via IP:port. When I dig deeper, I found `/api/getLogs` and I was able to see the grpc error. It turns out my wget is spamming logs as it takes minutes to download something, I'm hoping add the `-q` to that script could make OliveTin run longer without crashing.

Printing and looping around some large junk file repeated isn't the typical use case for OliveTin, however, with misconfiguration or verbose scripts or programs, the 4MB default limit could be reached. I could recommend increasing grpc limit, logrotation or better error handling in WebUI. Alternative, I suggest updating the documentation for fetch buttons errors; in the case user gets `e.logs is undefined` the user should make their script less verbose or use output redirection, as reverse proxy or network problem is not the cause for it.

**Comment by jamesread** [comment]
Hey, thanks for raising an issue for this, and sorry that you've been waiting a little while for me to reply, I've not had time to do open source projects during December unfortunately, however, I'm getting some time back now :-) Anyway, sorry that you're having this issue.

OliveTin stores all logs in memory, this isn't necessarily a problem if you have actions with modest output, but actually each time you execute, it's going to use 4Mb of RAM. The problem is that the logs view specifically is sent for all actions in RAM to the browser at once, on page load - and this probably isn't a sensible design at all.

This could be worked around by sending the list of executions, without the log data attached, and only load the log when someone requests it - by opening the log view. That would be a much better way to get around the gRPC "limit". This is going to take a bit of time to implement though. 

There is a quick and dirty workaround available, I could add a new setting to increase the gRPC message limit size ( which is 4MB - https://pkg.go.dev/google.golang.org/grpc#MaxCallRecvMsgSize ) , and if it's urgent for you I can hack that in pretty quickly for you.

**Comment by vttc08** [comment]
Hi, thanks for the response. I've had the same problem again even after suppressing my actions log. It seems just executing actions many times even without heavy logging would cause logs to be full because every execution logs some metadata. Knowing this, I think the only reliable solution I can use it crontab and `systemctl restart OliveTin`. It is not urgent for me to solve it, gRPC limit size could be helpful but I can wait for the proper implementation. Since I use OliveTin as a "API gateway" to access system resource for automated actions, which idk is the use case OliveTin designed for, the logs will pile up sooner or later due to automation.

**Comment by jamesread** [comment]
Heya @vttc08 , release 2025.2.19 includes the fix for this - only 10x logs are sent to the browser at once (this count is configurable), which should stop those gRPC encode errors and lots of browser lag. 

Could you test and let me know? Thanks!

**Comment by vttc08** [comment]
Hi, I've tested the new version, and it appears the problem is solved. When running the same action that spam the log, the WebUI remain usable after refresh despite the gRPC logs exceed 4 MB. I hope OliveTin will now run stably in my environment with my automation and actions.

**Comment by fricpa** [comment]
Thanks for these clarifications. I am facing exactly the same issue:

![Image](https://github.com/user-attachments/assets/bc675c69-451f-4806-b8a2-2104c29f4407)

I will try with the latest version and reopen here if we still experience the problem...

PS: the old doc link in the error message pointed to https://docs.olivetin.app/err-fetch-buttons.html which is now dead, I hope the link was adjusted to the new https://docs.olivetin.app/troubleshooting/err-fetch-buttons.html

**Comment by fricpa** [comment]
The way the http request failed in this case was definitely funny and did not help to intuit what was wrong: http status code "429 Too Many Requests"

**Comment by fricpa** [comment]
I vote to reopen this, one of our users saw this after she left her tab open while a long running job was spewing hundreds of MB of logs: 

![Image](https://github.com/user-attachments/assets/b87f4d70-da0f-4cc5-81cf-21270f6fb0b8)

probably the chunking implementation has flaws...

**Comment by fricpa** [comment]
^^ this is OliveTin Version: 2025.4.22

**Comment by jamesread** [comment]
Hey @fricpa let's continue the discussion in #585  - I won't get notifications for comments in closed issues.
